services:
  lesson_bot:
    container_name: lesson_bot_container
    image: lesson_bot_image
    build:
      context: .
    env_file:
      - .env
    environment:
      BOT_TOKEN: "${BOT_TOKEN}"
    depends_on:
      - bot_db
  
  bot_db:
      container_name: postgres_container
      image: postgres:15
      volumes:
        - postgres_data:/data/postgres
      ports:
        - "5432:5432"
      env_file:
        - .env
      environment:
        PGDATA: /data/postgres
  
  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    profiles:
      - "dev"
    restart: on-failure
    env_file:
      - .env
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin

volumes:
  postgres_data:
  pgadmin_data:
